name: Let's Face Error

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Run Python Tests (Expecting Error)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # This will cause an error since requirements.txt doesn't exist
          pip install pytest  # Ensure pytest is installed

      - name: Run Tests
        run: python -m pytest tests/  # This will cause an error since the tests/ folder doesn't exist
